# Generated by Django 4.1.1 on 2022-09-13 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_post_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 13, 6, 38, 246750)),
        ),
    ]
