# Generated by Django 4.1.1 on 2022-09-13 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_post_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
